# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0443a0cb8cbf2c827f3d05b73b5da7a757d9fa13cd4f984209482b3611c5b06c7fb5322df136096dba215dcc24a4d5b2bdd5b10a645831472560833a1399afa

test:
  secret_key_base: ec51cf99be4c7aae2ff75c612a1b64605ec7721e8f2f2d1c05f825e1a84a1210e3241ac6936b2597b2fb855e270d392b0e50206b7dcae64c9cac27805f69e497

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
